version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data # Persist data locally
    restart: always
